# Generated by Django 5.0.7 on 2024-08-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSPAPIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(default='', max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_spapi_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
