from enum import Enum


class ReportType(Enum):
    GET_SALES_AND_TRAFFIC_REPORT = "GET_SALES_AND_TRAFFIC_REPORT"
    GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT = "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT"
    GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT = "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT"
    GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT = "GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT"
    GET_VENDOR_REAL_TIME_INVENTORY_REPORT = "GET_VENDOR_REAL_TIME_INVENTORY_REPORT"
    GET_VENDOR_REAL_TIME_TRAFFIC_REPORT = "GET_VENDOR_REAL_TIME_TRAFFIC_REPORT"
    GET_VENDOR_REAL_TIME_SALES_REPORT = "GET_VENDOR_REAL_TIME_SALES_REPORT"
    GET_VENDOR_SALES_REPORT = "GET_VENDOR_SALES_REPORT"
    GET_VENDOR_FORECASTING_REPORT = "GET_VENDOR_FORECASTING_REPORT"
